// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var name = "Joe";

var greeting = "Hello\nWorld\n👋\n" + name + "\n";

var message = "Today I am " + 10 + " years old.";

var r = /b/g;

var a = Caml_obj.caml_equal([
      1,
      2
    ], [
      1,
      2
    ]);

var b = [
  1,
  2
] === [
  1,
  2
];

var myTuple = [
  1,
  2
];

var c = myTuple === myTuple;

var floatExample = 0.5 + 0.6;

var multilineGreeting = "Hello\n world!";

var gretting = "Hello world!";

var age = 10;

var firstLetterOfAlphabet = /* "a" */97;

exports.multilineGreeting = multilineGreeting;
exports.gretting = gretting;
exports.name = name;
exports.greeting = greeting;
exports.age = age;
exports.message = message;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.r = r;
exports.a = a;
exports.b = b;
exports.myTuple = myTuple;
exports.c = c;
exports.floatExample = floatExample;
/* a Not a pure module */
