// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var meNextYear = {
  age: 21,
  name: "Big ReScript"
};

var baby = {
  name: "Baby ReScript",
  age: 5
};

baby.age = baby.age + 1 | 0;

function getAge(entity) {
  return entity.age;
}

var me2 = {
  age: 20,
  name: "Big ReScript"
};

var name = "Big ReScript";

var kraken = {
  age: 9999,
  hasTentacles: true
};

var me = {
  age: 5,
  name: "Baby ReScript"
};

var age = 9999;

exports.me2 = me2;
exports.name = name;
exports.meNextYear = meNextYear;
exports.baby = baby;
exports.getAge = getAge;
exports.kraken = kraken;
exports.me = me;
exports.age = age;
/*  Not a pure module */
