// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

var greetings = [
  "hello",
  "world",
  "how are you"
];

var payloadResults = [
  {
    TAG: /* Ok */0,
    _0: {
      data: "hi"
    }
  },
  {
    TAG: /* Ok */0,
    _0: {
      data: "bye"
    }
  },
  {
    TAG: /* Error */1,
    _0: "Something wrong happened!"
  }
];

var gpa = 2.1 + 10;

var score = 10;

var myInt = 9;

var x = 10;

var a = [
  10,
  20,
  20
];

var b = [
  10.5,
  20.5,
  20.5
];

var buddy = [
  10,
  20,
  20
];

var age = 10;

exports.score = score;
exports.myInt = myInt;
exports.add = add;
exports.x = x;
exports.a = a;
exports.b = b;
exports.buddy = buddy;
exports.greetings = greetings;
exports.payloadResults = payloadResults;
exports.age = age;
exports.gpa = gpa;
/* No side effect */
