// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var coordinates2 = [
  60,
  20,
  30
];

var ageAndName = [
  24,
  "Lil' ReScript"
];

var my3dCoordinates = [
  20.0,
  30.5,
  100.0
];

var y = 30.5;

var coordinates1 = [
  10,
  20,
  30
];

var c1x = 10;

exports.ageAndName = ageAndName;
exports.my3dCoordinates = my3dCoordinates;
exports.y = y;
exports.coordinates1 = coordinates1;
exports.c1x = c1x;
exports.coordinates2 = coordinates2;
/* No side effect */
