// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var x = {
  contents: 5
};

x.contents = x.contents + 1 | 0;

var message = "world!";

var str = "Hello " + message;

var thisIsTrue = true;

var thisIsFalse = false;

var thisIsFalseTwo = false;

var orOperator = true;

var andOperator = true;

var greaterThanOrEqualToOperator = true;

var lessThanOrEqualToOperator = true;

var lessThanOperator = true;

var greaterThanOperator = true;

var equalOperator = true;

var notEqualOperator = true;

var deepEqualityOperator = true;

var deepNotEqaulOperator = true;

exports.x = x;
exports.message = message;
exports.str = str;
exports.thisIsTrue = thisIsTrue;
exports.thisIsFalse = thisIsFalse;
exports.thisIsFalseTwo = thisIsFalseTwo;
exports.orOperator = orOperator;
exports.andOperator = andOperator;
exports.greaterThanOrEqualToOperator = greaterThanOrEqualToOperator;
exports.lessThanOrEqualToOperator = lessThanOrEqualToOperator;
exports.lessThanOperator = lessThanOperator;
exports.greaterThanOperator = greaterThanOperator;
exports.equalOperator = equalOperator;
exports.notEqualOperator = notEqualOperator;
exports.deepEqualityOperator = deepEqualityOperator;
exports.deepNotEqaulOperator = deepNotEqaulOperator;
/*  Not a pure module */
