// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


document.addEventListener("mouseup", (function (_event) {
        console.log("clicked!");
        
      }));

var loc = document.location;

document.location.href = "http://www.rescript-lang.org";

exports.loc = loc;
/*  Not a pure module */
