// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TestJs = require("./test.js");

var me = {
  age: "hello!"
};

var age = me.age;

var student1 = TestJs.student1;

student1.name = "Mary";

console.log(student1);

exports.me = me;
exports.age = age;
exports.student1 = student1;
/* age Not a pure module */
