// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var myArray = [
  "hello",
  "world",
  "how are you"
];

var firstItem = Caml_array.get(myArray, 0);

Caml_array.set(myArray, 0, "hey");

exports.myArray = myArray;
exports.firstItem = firstItem;
/*  Not a pure module */
