// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

var anotherList = {
  hd: 0,
  tl: myList
};

var message = myList ? "The head of the list is the string " + (1).toString() : "This list is empty";

exports.myList = myList;
exports.anotherList = anotherList;
exports.message = message;
/* message Not a pure module */
